// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAvgLUAyTSU3wYXeZo8-ksFy1WUnSXlg',
    appId: '1:611207457088:web:55f81be01699ee0b3cf2a5',
    messagingSenderId: '611207457088',
    projectId: 'dar-project-3825f',
    authDomain: 'dar-project-3825f.firebaseapp.com',
    storageBucket: 'dar-project-3825f.appspot.com',
    measurementId: 'G-1KCN2Y3T75',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXbeV8Chao8H-_tPDKJORTerHTq31Jf8s',
    appId: '1:611207457088:ios:611827c6de1236773cf2a5',
    messagingSenderId: '611207457088',
    projectId: 'dar-project-3825f',
    storageBucket: 'dar-project-3825f.appspot.com',
    iosClientId: '611207457088-j0dsl5dqgptvfeu14b8ci25bp0befsl0.apps.googleusercontent.com',
    iosBundleId: 'com.example.dar',
  );
}
